- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade

- name: Install Kubernetes addons
  hosts: localhost
  environment:
    # TODO don't hard code?
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - cilium
